- include_tasks: get NFS Server.yml

- name: Install NFS
  become: true
  ansible.builtin.dnf:
    name: nfs-utils
    state: latest

- name: Create mount directory
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

- name: Mount NFS volume
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ export }}"
    path: "{{ mountpoint }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    boot: true
  become: true