Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora39"

  # VirtIO GPU
  # works: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1482
  config.vm.provider :libvirt do |libvirt|
    libvirt.video_type = 'virtio'
    libvirt.video_accel3d = true
    libvirt.graphics_gl = true
    libvirt.graphics_type = 'spice'
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
  end

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
