- name: Create repo dir
  ansible.builtin.file:
    path: "{{ repo_dir }}"
    state: directory
    mode: '0755'

# - name: Configure repo dir
#   become: true
#   ansible.builtin.lineinfile:
#     path: "{{ config_file }}"
#     regexp: '^# repodir = '
#     line: "repodir = {{ repo_dir }}"

- name: Set repodir in conf
  become: true
  community.general.ini_file:
    path: "{{ config_file }}"
    section: main
    option: repodir
    value: "{{ repo_dir }}"
    mode: "644"

# from: https://github.com/buckaroogeek/ansible-role-fedora-dnf-local-plugin
# set cachedir if defined
- name: Set cachedir if defined
  become: true
  community.general.ini_file:
    path: "{{ config_file }}"
    section: createrepo
    option: cachedir
    value: "{{ cache_dir }}"
    mode: "644"
  when: (cache_dir is defined) and (cache_dir|length > 0)